# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-31 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_id', models.IntegerField(verbose_name='用户ID')),
                ('to_id', models.IntegerField(verbose_name='好友ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='对方是否同意')),
            ],
            options={
                'verbose_name': '好友列表',
                'verbose_name_plural': '好友列表',
                'db_table': 'friends',
            },
        ),
    ]
