# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-01 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=100, verbose_name='私信留言')),
                ('sender', models.CharField(max_length=20, verbose_name='寄信人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letter.Friend')),
            ],
            options={
                'verbose_name': '私信',
                'verbose_name_plural': '私信',
                'db_table': 'letters',
            },
        ),
    ]
