# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-03 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0002_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='消息是否已读'),
        ),
    ]
