# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-18 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='video',
            field=models.CharField(default='', max_length=100, verbose_name='视频URL'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='封面'),
        ),
    ]
