# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-22 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0003_auto_20200218_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.CharField(max_length=100, verbose_name='文件路径')),
                ('reference_number', models.IntegerField(verbose_name='引用数')),
            ],
        ),
    ]
