# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-23 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0004_filereference'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFavourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('essay_id', models.IntegerField(verbose_name='文章id')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'db_table': 'myfavourite',
            },
        ),
        migrations.AlterModelOptions(
            name='filereference',
            options={'verbose_name': '文件引用数', 'verbose_name_plural': '文件引用数'},
        ),
        migrations.AlterModelTable(
            name='filereference',
            table='reference',
        ),
    ]
